<?php

namespace AppBundle\Repository;

/**
 * BudgetPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
